ELECTORAL_VOTES_BY_STATEPOSTAL = {
    "AK": 3,
    "AL": 9,
    "AR": 6,
    "AZ": 11,
    "CA": 55,
    "CO": 9,
    "CT": 7,
    "DC": 3,
    "DE": 3,
    "FL": 29,
    "GA": 16,
    "HI": 4,
    "IA": 6,
    "ID": 4,
    "IL": 20,
    "IN": 11,
    "KS": 6,
    "KY": 8,
    "LA": 8,
    "MA": 11,
    "MD": 10,
    "district-20005": 2,
    "district-20026": 1,
    "district-20027": 1,
    "MI": 16,
    "MN": 10,
    "MO": 10,
    "MS": 6,
    "MT": 3,
    "NC": 15,
    "ND": 3,
    "district-28004": 2,
    "district-28006": 1,
    "district-28007": 1,
    "district-28008": 1,
    "NH": 4,
    "NJ": 14,
    "NM": 5,
    "NV": 6,
    "NY": 29,
    "OH": 18,
    "OK": 7,
    "OR": 7,
    "PA": 20,
    "RI": 4,
    "SC": 9,
    "SD": 3,
    "TN": 11,
    "TX": 38,
    "UT": 6,
    "VA": 13,
    "VT": 3,
    "WA": 12,
    "WI": 10,
    "WV": 5,
    "WY": 3,
}

PREZ_REPORTING_UNIT_TO_DISTRICT_LABELS = {
    "district-20005": {
        "reportingunitname": "At Large",
        "label": "Maine At Large"
    },
    "district-20026": {
        "reportingunitname": "District 1",
        "label": "Maine Dist. 1"
    },
    "district-20027": {
        "reportingunitname": "District 2",
        "label": "Maine Dist. 2"
    },
    "district-28004": {
        "reportingunitname": "At Large",
        "label": "Nebraska At Large"
    },
    "district-28006": {
        "reportingunitname": "District 1",
        "label": "Nebraska Dist. 1"
    },
    "district-28007": {
        "reportingunitname": "District 2",
        "label": "Nebraska Dist. 2"
    },
    "district-28008": {
        "reportingunitname": "District 3",
        "label": "Nebraska Dist. 3"
    }
}

PREZ_STATE_TO_LABEL = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "D.C.",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "US": "National",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming"
}